# .github/workflows/docker.yml
name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Frontend
        run: |
          docker build -t yutingchen1008/2025cloud:frontend ./frontend
          docker push yutingchen1008/2025cloud:frontend

      - name: Build and Push Backend
        run: |
          docker build -t yutingchen1008/2025cloud:backend ./backend
          docker push yutingchen1008/2025cloud:backend
